#!/usr/bin/env zsh
# My .zshenv file


# Add ~/.local/bin to $PATH
XDG_EXECUTABLE_HOME="${XDG_EXECUTABLE_HOME:-$HOME/.local/bin}"
if [[ ":$PATH:" == *":$XDG_EXECUTABLE_HOME:"* ]]; then
    PATH="$XDG_EXECUTABLE_HOME:$PATH"
fi
export XDG_EXECUTABLE_HOME

# Path to zsh history file.
export HISTFILE="$XDG_CACHE_HOME/zsh/history"

# Path to zinit installation and cache folder.
ZINIT_HOME="$XDG_DATA_HOME/zinit"
typeset -A ZINIT
ZINIT[HOME_DIR]=$ZINIT_HOME
ZINIT[ZCOMPDUMP_PATH]="$XDG_CACHE_HOME/zsh/zcompdump"
export ZINIT_HOME ZINIT

# Path to less hystory file
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# Path to cuda cache
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"

# Paths for miniconda
CONDARC="$XDG_CONFIG_HOME/conda/condarc"
CONDA_ENVS_PATH="$XDG_DATA_HOME/conda/envs"
CONDA_PKGS_DIRS="$XDG_CACHE_HOME/conda/pkgs"
CONDA_BLD_PATH="$XDG_CACHE_HOME/conda/build"
export CONDARC CONDA_ENVS_PATH CONDA_PKGS_DIRS CONDA_BLD_PATH

# Path for micromamba
MAMBA_EXE="$XDG_EXECUTABLE_HOME/micromamba"
MAMBARC="$XDG_CONFIG_HOME/mamba/mambarc"
MAMBA_ROOT_PREFIX="$XDG_DATA_HOME/micromamba"
export MAMBA_EXE MAMBARC MAMBA_ROOT_PREFIX

# Path for GnuPG
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# Path for Ipython
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"

# Path for Sops Age key
export SOPS_AGE_KEY_FILE="$XDG_CONFIG_HOME/sops/age/key.txt"

# Path for Editor and Visual
EDITOR="code"
VISUAL="$EDITOR"
export EDITOR VISUAL

# Path for wget
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
