#!/usr/bin/env zsh
# My .zshenv file

# Add ~/.local/bin to $PATH
PATH="$HOME/.local/bin:$PATH"

# Path to zsh history file.
export HISTFILE="$XDG_CACHE_HOME/zsh/history"

# Path to zinit installation and cache folder.
ZINIT_HOME="$XDG_DATA_HOME/zinit"
typeset -A ZINIT
ZINIT[HOME_DIR]=$ZINIT_HOME
ZINIT[ZCOMPDUMP_PATH]="$XDG_CACHE_HOME/zsh/zcompdump"
export ZINIT_HOME ZINIT

# Path to less hystory file
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"

# Path to cuda cache
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"

# Paths for miniconda
CONDARC="$XDG_CONFIG_HOME/conda/condarc"
CONDA_ENVS_PATH="$XDG_DATA_HOME/conda/envs"
CONDA_PKGS_DIRS="$XDG_CACHE_HOME/conda/pkgs"
CONDA_BLD_PATH="$XDG_CACHE_HOME/conda/build"
export CONDARC CONDA_ENVS_PATH CONDA_PKGS_DIRS CONDA_BLD_PATH

# Path for micromamba
MAMBA_EXE="$HOME/.local/bin/micromamba"
MAMBARC="$XDG_CONFIG_HOME/mamba/mambarc"
MAMBA_ROOT_PREFIX="$XDG_DATA_HOME/micromamba"
export MAMBA_EXE MAMBARC MAMBA_ROOT_PREFIX

# Path for GnuPG
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# Path for Ipython
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
